# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FlashLapse_CP.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 492)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../_image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image_Frame = QtWidgets.QLabel(self.centralwidget)
        self.Image_Frame.setGeometry(QtCore.QRect(480, 20, 300, 300))
        self.Image_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Image_Frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Image_Frame.setLineWidth(5)
        self.Image_Frame.setText("")
        self.Image_Frame.setPixmap(QtGui.QPixmap("../_image/background.png"))
        self.Image_Frame.setScaledContents(True)
        self.Image_Frame.setObjectName("Image_Frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(490, 400, 91, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.JPG = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.JPG.setChecked(True)
        self.JPG.setObjectName("JPG")
        self.verticalLayout_4.addWidget(self.JPG)
        self.PNG = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.PNG.setObjectName("PNG")
        self.verticalLayout_4.addWidget(self.PNG)
        self.Control_Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Control_Tab.setGeometry(QtCore.QRect(30, 20, 441, 431))
        self.Control_Tab.setObjectName("Control_Tab")
        self.Lighting = QtWidgets.QWidget()
        self.Lighting.setObjectName("Lighting")
        self.Lights = QtWidgets.QTabWidget(self.Lighting)
        self.Lights.setGeometry(QtCore.QRect(10, 10, 391, 381))
        self.Lights.setObjectName("Lights")
        self.Constant = QtWidgets.QWidget()
        self.Constant.setObjectName("Constant")
        self.Color_Frame = QtWidgets.QLabel(self.Constant)
        self.Color_Frame.setGeometry(QtCore.QRect(35, 30, 300, 300))
        self.Color_Frame.setText("")
        self.Color_Frame.setPixmap(QtGui.QPixmap("../_image/Color_None.png"))
        self.Color_Frame.setScaledContents(True)
        self.Color_Frame.setObjectName("Color_Frame")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.Constant)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(130, 140, 111, 71))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Full_Color_Select = QtWidgets.QComboBox(self.verticalLayoutWidget_6)
        self.Full_Color_Select.setFrame(True)
        self.Full_Color_Select.setObjectName("Full_Color_Select")
        self.Full_Color_Select.addItem("")
        self.Full_Color_Select.addItem("")
        self.Full_Color_Select.addItem("")
        self.Full_Color_Select.addItem("")
        self.Full_Color_Select.addItem("")
        self.verticalLayout_5.addWidget(self.Full_Color_Select)
        self.IR_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.IR_2.setObjectName("IR_2")
        self.verticalLayout_5.addWidget(self.IR_2)
        self.Lights.addTab(self.Constant, "")
        self.Presets = QtWidgets.QWidget()
        self.Presets.setObjectName("Presets")
        self.Presets1 = QtWidgets.QTabWidget(self.Presets)
        self.Presets1.setGeometry(QtCore.QRect(10, 10, 321, 331))
        self.Presets1.setObjectName("Presets1")
        self.IR = QtWidgets.QWidget()
        self.IR.setObjectName("IR")
        self.IR_Text = QtWidgets.QTextBrowser(self.IR)
        self.IR_Text.setGeometry(QtCore.QRect(10, 20, 290, 110))
        self.IR_Text.setObjectName("IR_Text")
        self.IR_Confirm = QtWidgets.QPushButton(self.IR)
        self.IR_Confirm.setEnabled(False)
        self.IR_Confirm.setGeometry(QtCore.QRect(50, 180, 211, 61))
        self.IR_Confirm.setObjectName("IR_Confirm")
        self.Presets1.addTab(self.IR, "")
        self.ROS = QtWidgets.QWidget()
        self.ROS.setObjectName("ROS")
        self.ROS_Text = QtWidgets.QTextBrowser(self.ROS)
        self.ROS_Text.setGeometry(QtCore.QRect(10, 20, 290, 110))
        self.ROS_Text.setObjectName("ROS_Text")
        self.Germi_Confirm = QtWidgets.QPushButton(self.ROS)
        self.Germi_Confirm.setGeometry(QtCore.QRect(220, 260, 81, 23))
        self.Germi_Confirm.setObjectName("Germi_Confirm")
        self.layoutWidget_2 = QtWidgets.QWidget(self.ROS)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 160, 291, 90))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Flush_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.Flush_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Flush_2.setObjectName("Flush_2")
        self.horizontalLayout_3.addWidget(self.Flush_2)
        self.Flush_Frequency = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.Flush_Frequency.setMinimum(1)
        self.Flush_Frequency.setMaximum(9999999)
        self.Flush_Frequency.setObjectName("Flush_Frequency")
        self.horizontalLayout_3.addWidget(self.Flush_Frequency)
        self.Presets1.addTab(self.ROS, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Disco = QtWidgets.QPushButton(self.tab)
        self.Disco.setGeometry(QtCore.QRect(40, 70, 231, 141))
        self.Disco.setObjectName("Disco")
        self.Presets1.addTab(self.tab, "")
        self.Lights.addTab(self.Presets, "")
        self.Control_Tab.addTab(self.Lighting, "")
        self.Imaging = QtWidgets.QWidget()
        self.Imaging.setObjectName("Imaging")
        self.layoutWidget = QtWidgets.QWidget(self.Imaging)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 391, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Image_Title = QtWidgets.QLabel(self.layoutWidget)
        self.Image_Title.setObjectName("Image_Title")
        self.verticalLayout.addWidget(self.Image_Title)
        self.IST_Editor = QtWidgets.QLineEdit(self.layoutWidget)
        self.IST_Editor.setEnabled(True)
        self.IST_Editor.setObjectName("IST_Editor")
        self.verticalLayout.addWidget(self.IST_Editor)
        self.Image_Interval = QtWidgets.QLabel(self.layoutWidget)
        self.Image_Interval.setObjectName("Image_Interval")
        self.verticalLayout.addWidget(self.Image_Interval)
        self.ICI_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.ICI_spinBox.setEnabled(False)
        self.ICI_spinBox.setMaximum(9999999)
        self.ICI_spinBox.setObjectName("ICI_spinBox")
        self.verticalLayout.addWidget(self.ICI_spinBox)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Image_Duration = QtWidgets.QLabel(self.layoutWidget)
        self.Image_Duration.setObjectName("Image_Duration")
        self.verticalLayout_2.addWidget(self.Image_Duration)
        self.ISD_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.ISD_spinBox.setEnabled(False)
        self.ISD_spinBox.setMaximum(9999999)
        self.ISD_spinBox.setObjectName("ISD_spinBox")
        self.verticalLayout_2.addWidget(self.ISD_spinBox)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.Directory_Label = QtWidgets.QLabel(self.layoutWidget)
        self.Directory_Label.setEnabled(True)
        self.Directory_Label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Directory_Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Directory_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Directory_Label.setObjectName("Directory_Label")
        self.verticalLayout_2.addWidget(self.Directory_Label)
        self.Storage_Directory = QtWidgets.QPushButton(self.layoutWidget)
        self.Storage_Directory.setEnabled(False)
        self.Storage_Directory.setCheckable(False)
        self.Storage_Directory.setObjectName("Storage_Directory")
        self.verticalLayout_2.addWidget(self.Storage_Directory)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.Live_Feed = QtWidgets.QPushButton(self.layoutWidget)
        self.Live_Feed.setObjectName("Live_Feed")
        self.verticalLayout_3.addWidget(self.Live_Feed)
        self.layoutWidget1 = QtWidgets.QWidget(self.Imaging)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 340, 411, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Progress_Label = QtWidgets.QLabel(self.layoutWidget1)
        self.Progress_Label.setObjectName("Progress_Label")
        self.verticalLayout_6.addWidget(self.Progress_Label)
        self.Progress_Bar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.Progress_Bar.setEnabled(False)
        self.Progress_Bar.setProperty("value", 0)
        self.Progress_Bar.setObjectName("Progress_Bar")
        self.verticalLayout_6.addWidget(self.Progress_Bar)
        self.Control_Tab.addTab(self.Imaging, "")
        self.Cloud = QtWidgets.QWidget()
        self.Cloud.setObjectName("Cloud")
        self.Service_Select = QtWidgets.QTabWidget(self.Cloud)
        self.Service_Select.setEnabled(True)
        self.Service_Select.setGeometry(QtCore.QRect(10, 10, 401, 271))
        self.Service_Select.setObjectName("Service_Select")
        self.Dropbox = QtWidgets.QWidget()
        self.Dropbox.setObjectName("Dropbox")
        self.label = QtWidgets.QLabel(self.Dropbox)
        self.label.setGeometry(QtCore.QRect(60, 10, 271, 140))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../_image/dropbox_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Dropbox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(50, 130, 291, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.Dropbox_Email_Prompt = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Dropbox_Email_Prompt.setObjectName("Dropbox_Email_Prompt")
        self.verticalLayout_9.addWidget(self.Dropbox_Email_Prompt)
        self.Dropbox_Email = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.Dropbox_Email.setObjectName("Dropbox_Email")
        self.verticalLayout_9.addWidget(self.Dropbox_Email)
        self.Dropbox_Confirm = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Dropbox_Confirm.setEnabled(False)
        self.Dropbox_Confirm.setObjectName("Dropbox_Confirm")
        self.verticalLayout_9.addWidget(self.Dropbox_Confirm)
        self.Service_Select.addTab(self.Dropbox, "")
        self.CyVerse = QtWidgets.QWidget()
        self.CyVerse.setObjectName("CyVerse")
        self.label_2 = QtWidgets.QLabel(self.CyVerse)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 281, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../_image/cyverse_logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.CyVerse)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(50, 130, 291, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.CyVerse_Email_Prompt = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.CyVerse_Email_Prompt.setObjectName("CyVerse_Email_Prompt")
        self.verticalLayout_10.addWidget(self.CyVerse_Email_Prompt)
        self.CyVerse_Email = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.CyVerse_Email.setEnabled(False)
        self.CyVerse_Email.setObjectName("CyVerse_Email")
        self.verticalLayout_10.addWidget(self.CyVerse_Email)
        self.CyVerse_Confirm = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.CyVerse_Confirm.setEnabled(False)
        self.CyVerse_Confirm.setObjectName("CyVerse_Confirm")
        self.verticalLayout_10.addWidget(self.CyVerse_Confirm)
        self.Service_Select.addTab(self.CyVerse, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Cloud)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 330, 351, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Frequency_Off = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.Frequency_Off.setEnabled(False)
        self.Frequency_Off.setCheckable(True)
        self.Frequency_Off.setChecked(False)
        self.Frequency_Off.setObjectName("Frequency_Off")
        self.horizontalLayout_6.addWidget(self.Frequency_Off)
        self.Frequency_Low = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.Frequency_Low.setEnabled(False)
        self.Frequency_Low.setObjectName("Frequency_Low")
        self.horizontalLayout_6.addWidget(self.Frequency_Low)
        self.Frequency_Average = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.Frequency_Average.setEnabled(False)
        self.Frequency_Average.setChecked(True)
        self.Frequency_Average.setObjectName("Frequency_Average")
        self.horizontalLayout_6.addWidget(self.Frequency_Average)
        self.Frequency_High = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.Frequency_High.setEnabled(False)
        self.Frequency_High.setObjectName("Frequency_High")
        self.horizontalLayout_6.addWidget(self.Frequency_High)
        self.Email_Update_Prompt = QtWidgets.QLabel(self.Cloud)
        self.Email_Update_Prompt.setGeometry(QtCore.QRect(40, 300, 221, 31))
        self.Email_Update_Prompt.setObjectName("Email_Update_Prompt")
        self.Control_Tab.addTab(self.Cloud, "")
        self.Start_Imaging = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.Start_Imaging.setEnabled(False)
        self.Start_Imaging.setGeometry(QtCore.QRect(600, 400, 191, 51))
        self.Start_Imaging.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../_image/Start-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Start_Imaging.setIcon(icon1)
        self.Start_Imaging.setIconSize(QtCore.QSize(35, 35))
        self.Start_Imaging.setObjectName("Start_Imaging")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(490, 330, 161, 51))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Local_Storage = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.Local_Storage.setChecked(True)
        self.Local_Storage.setObjectName("Local_Storage")
        self.verticalLayout_12.addWidget(self.Local_Storage)
        self.Cloud_Sync = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.Cloud_Sync.setEnabled(False)
        self.Cloud_Sync.setObjectName("Cloud_Sync")
        self.verticalLayout_12.addWidget(self.Cloud_Sync)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(680, 320, 101, 80))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Snapshot = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.Snapshot.setEnabled(True)
        self.Snapshot.setObjectName("Snapshot")
        self.verticalLayout_13.addWidget(self.Snapshot)
        self.Flush = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.Flush.setObjectName("Flush")
        self.verticalLayout_13.addWidget(self.Flush)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_Directory = QtWidgets.QAction(MainWindow)
        self.actionOpen_Directory.setEnabled(False)
        self.actionOpen_Directory.setObjectName("actionOpen_Directory")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCreate_Timelapse = QtWidgets.QAction(MainWindow)
        self.actionCreate_Timelapse.setObjectName("actionCreate_Timelapse")

        self.retranslateUi(MainWindow)
        self.Control_Tab.setCurrentIndex(0)
        self.Lights.setCurrentIndex(0)
        self.Presets1.setCurrentIndex(0)
        self.Service_Select.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FlashLapse Commad Point"))
        self.JPG.setText(_translate("MainWindow", "JPG"))
        self.PNG.setText(_translate("MainWindow", "PNG"))
        self.Full_Color_Select.setCurrentText(_translate("MainWindow", "None"))
        self.Full_Color_Select.setItemText(0, _translate("MainWindow", "None"))
        self.Full_Color_Select.setItemText(1, _translate("MainWindow", "White"))
        self.Full_Color_Select.setItemText(2, _translate("MainWindow", "Red"))
        self.Full_Color_Select.setItemText(3, _translate("MainWindow", "Green"))
        self.Full_Color_Select.setItemText(4, _translate("MainWindow", "Blue"))
        self.IR_2.setText(_translate("MainWindow", "Infrared: OFF"))
        self.Lights.setTabText(self.Lights.indexOf(self.Constant), _translate("MainWindow", "Constant"))
        self.IR_Text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.1pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">IR light triggered five seconds before imaging, no other light sourcewill be present in the system.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt; font-weight:600; color:#aa0000;\">Can only be selected after imaging parameters are confirmed.</span></p></body></html>"))
        self.IR_Confirm.setText(_translate("MainWindow", "Start IR Image Sequence"))
        self.Presets1.setTabText(self.Presets1.indexOf(self.IR), _translate("MainWindow", "IR-Imaging"))
        self.ROS_Text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.1pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A 5 second liquid flow triggered periodically thoughout the image sequence.</p></body></html>"))
        self.Germi_Confirm.setText(_translate("MainWindow", "Confirm "))
        self.Flush_2.setText(_translate("MainWindow", "Flush Frequency:"))
        self.Flush_Frequency.setSuffix(_translate("MainWindow", " Min/flush"))
        self.Presets1.setTabText(self.Presets1.indexOf(self.ROS), _translate("MainWindow", "ROS-Imaging"))
        self.Disco.setText(_translate("MainWindow", "Start!"))
        self.Presets1.setTabText(self.Presets1.indexOf(self.tab), _translate("MainWindow", "Disco"))
        self.Lights.setTabText(self.Lights.indexOf(self.Presets), _translate("MainWindow", "Presets"))
        self.Control_Tab.setTabText(self.Control_Tab.indexOf(self.Lighting), _translate("MainWindow", "Lighting"))
        self.Image_Title.setText(_translate("MainWindow", "Image Sequence Title"))
        self.Image_Interval.setText(_translate("MainWindow", "Image Capture Interval"))
        self.ICI_spinBox.setSuffix(_translate("MainWindow", " s"))
        self.Image_Duration.setText(_translate("MainWindow", "Image Sequence Duration"))
        self.ISD_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.Directory_Label.setText(_translate("MainWindow", "Storage Directory Not Selected"))
        self.Storage_Directory.setText(_translate("MainWindow", "Select Storage Directory"))
        self.Live_Feed.setText(_translate("MainWindow", "Start Live Feed (30s)"))
        self.Progress_Label.setText(_translate("MainWindow", "Progress:"))
        self.Control_Tab.setTabText(self.Control_Tab.indexOf(self.Imaging), _translate("MainWindow", "Imaging"))
        self.Dropbox_Email_Prompt.setText(_translate("MainWindow", "Please Enter Your Email Adress: "))
        self.Dropbox_Confirm.setText(_translate("MainWindow", "Confirm Email"))
        self.Service_Select.setTabText(self.Service_Select.indexOf(self.Dropbox), _translate("MainWindow", "Dropbox"))
        self.CyVerse_Email_Prompt.setText(_translate("MainWindow", "Please Enter Your Email Adress:"))
        self.CyVerse_Confirm.setText(_translate("MainWindow", "Confirm Email"))
        self.Service_Select.setTabText(self.Service_Select.indexOf(self.CyVerse), _translate("MainWindow", "CyVerse "))
        self.Frequency_Off.setText(_translate("MainWindow", "OFF"))
        self.Frequency_Low.setText(_translate("MainWindow", "LOW"))
        self.Frequency_Average.setText(_translate("MainWindow", "AVERAGE"))
        self.Frequency_High.setText(_translate("MainWindow", "HIGH"))
        self.Email_Update_Prompt.setText(_translate("MainWindow", "Email Status Update Frequency:"))
        self.Control_Tab.setTabText(self.Control_Tab.indexOf(self.Cloud), _translate("MainWindow", "Cloud"))
        self.Start_Imaging.setText(_translate("MainWindow", "Start Image Sequence"))
        self.Local_Storage.setText(_translate("MainWindow", "Local Storage"))
        self.Cloud_Sync.setText(_translate("MainWindow", "Cloud Sync"))
        self.Snapshot.setText(_translate("MainWindow", "Snapshot"))
        self.Flush.setText(_translate("MainWindow", "Flush"))
        self.actionOpen_Directory.setText(_translate("MainWindow", "Open Directory"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCreate_Timelapse.setText(_translate("MainWindow", "Create Timelapse"))

